version: '3.9'
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/contacts_db
      - JWT_SECRET=dev_secret_change_me
      - CLIENT_URL=http://localhost:5173
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  web:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - api
volumes:
  mongo_data:
