services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb+srv://Shivank79_db_user:k.bQ39B88@cluster0.s5r9fje.mongodb.net/contactmanager?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=change_me_in_prod
      - CLIENT_URL=http://localhost:5173
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  mongo_data: