# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: contact-manager
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: contact-manager
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
