name: MERN CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
       
      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm ci
       
      - name: Run Lint
        run: |
          cd ${{ matrix.service }}
          npm run lint
       
      - name: Run Tests
        run: |
          cd ${{ matrix.service }}
          npm test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test-lint
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
       
      - name: Build and Push action for frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/contact-manager-frontend:${{github.run_id}}

      - name: Build and Push action for backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/contact-manager-backend:${{github.run_id}}


  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
       
      - name: Update tag in Helm chart
        run: |
          for service in frontend backend; do
            sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" helm/contact-manager-chart/values.yaml
          done
       
      - name: Commit and Push changes
        run: |
          git config --global user.name "shivank kumar"
          git config --global user.email "kumarshivank799@gmail.com"
          git add helm/contact-manager-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }} in Helm chart" || echo "No changes to commit"
          git push origin main