name: MERN CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm ci

      - name: Run Lint
        run: |
          cd ${{ matrix.service }}
          npm run lint

      - name: Run Tests
        run: |
          cd ${{ matrix.service }}
          npm test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test-lint
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}
          logout: true

      - name: Build and Push Docker Image
        run: |
          IMAGE=shivank79/${{ matrix.service }}:${{ github.sha }}
          docker build -t $IMAGE ./${{ matrix.service }}
          docker push $IMAGE
          echo "$IMAGE" >> $GITHUB_STEP_SUMMARY

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          for service in frontend backend; do
           sed -i 's/tag: .*/tag: "${{github.run_id}}"/' Helm/contact-manager/values.yaml

      - name: Commit and Push changes
        run: |
          git config --global user.name "shivank kumar"
          git config --global user.email "kumarshivank799@gmail.com"
          git add Helm/contact-manager/values.yaml
          git commit -m "Update image tag to ${{ github.sha }} in Helm chart" || echo "No changes to commit"
          git push origin main
